knife4j:
  # 开启增强配置
  enable: true
spring:
  application:
    name: tcc-order
  datasource:
    username: root
    password: root
    jdbc-url: jdbc:mysql://192.168.11.140:33806/seata_order?serverTimezone=Asia/Chongqing&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&verifyServerCertificate=false&autoReconnct=true&autoReconnectForPools=true&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.11.140:8848
        username: nacos
        password: nacos
        namespace: "5b08206e-4d0a-4e11-9bf6-18093dd62b31"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
server:
  port: 8081
## 日志
logging:
  level:
    com.jackgreek: debug
ribbon:
  ReadTimeout: 500000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 300000 #ribbon请求连接的超时时间，默认值2000